# Generated by Django 2.2.16 on 2024-02-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230421_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/1', verbose_name='Картинка'),
        ),
    ]
