INDEX_URL_NAME = 'posts:index'
GROUP_LIST_URL_NAME = 'posts:group_list'
PROFILE_URL_NAME = 'posts:profile'
POST_DETAIL_URL_NAME = 'posts:post_detail'
POST_EDIT_URL_NAME = 'posts:post_edit'
POST_CREATE_URL_NAME = 'posts:create_post'
FOLLOW_INDEX_URL_NAME = 'posts:follow_index'
POST_ADD_COMMENT = 'posts:add_comment'

POST_ADD_COMMENT_TEMPLATE = 'posts/post_detail.html'
INDEX_TEMPLATE = 'posts/index.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_URL_TEMPLATE = 'posts/profile.html'
POST_DETAIL_URL_TEMPLATE = 'posts/post_detail.html'
POST_EDIT_URL_NAME_TEMPLATE = 'posts/create_post.html'
POST_CREATE_URL_TEMPLATE = 'posts/create_post.html'
FOLLOW_INDEX_TEMPLATE = 'posts/follow.html'
